### ISSUE TITLE
Add static support

### ISSUE THREAD

**Issue by malept** [malept/thermite#22]
See:

* https://github.com/steveklabnik/ruby-sys/pull/16
* https://github.com/d-unseductable/ruru/issues/50

**Comment by ianks** [comment]
This would be such a great improvement. Deploying Rust extensions becomes tedious without this. I am working a gem with bindings to `woothee-rust` and downloading the compiled lib is a great option for deploying to servers without an updated version of Rust/Cargo. It will make installation for users as simple as a `bundle install`, thus increasing the adoption of Rust 👍

**Comment by malept** [comment]
Most of the hard part is dealing with non-Linux platforms, I would greatly appreciate help with Windows/macOS.

**Comment by ianks** [comment]
@malept Unforuntately I cannot help there (linux user). Even if Mac/Windows wasn't stable at first, I think this would still be a large win. Currently I cannot deploy rust extensions without it 😢

**Comment by malept** [comment]
@ianks have you tried using Ruru with the ruby-sys branch linked in the issue summary? I would be happy to get feedback on that.
