### ISSUE TITLE
Thermite does not recorgnize cargo workspace setups

### ISSUE THREAD

**Issue by matthiasbeyer** [malept/thermite#29]
I have a cargo workspace setup, but thermite doesn't recognize that the `target` directory lives somewhere else than expected with default-cargo.

Is there a setting for configuring this? If not, this is a feature request! :smile:

**Comment by malept** [comment]
I will try to look into this sometime this weekend. Thank you for the feature request!

**Comment by matthiasbeyer** [comment]
I added an idea how this could be done in https://github.com/matthiasbeyer/thermite/commit/ffd7a1ffdb01dab04bd6def3702a95d252b824e4 - I have absolutely no idea whether this would suffice, though. It clearly would only cover one case, where the workspace lives one level above the current crate.

I did not test this, not even ran it. I just dumped my general idea in there and maybe it was a shot into the right direction...

**Comment by malept** [comment]
Thanks for prototyping something, that kicked off an idea for me.

Perhaps in the case of workspaces, `cargo_project_path` points to the workspace's top-level directory, and then the workspace member in question would be specified with `cargo_workspace_member`, which would be used to point to the appropriate `Cargo.toml`.

How does that sound?

**Comment by matthiasbeyer** [comment]
Sounds good, I guess...

**Comment by malept** [comment]
This is released in Thermite 0.11.0.
