### ISSUE TITLE
Config option for gems that can fail gracefully when trying to build optional rust extensions.

### ISSUE THREAD

**Issue by nomoon** [malept/thermite#4]
Right now the build task errors if there is no Rust, which isn't helpful when I want to fallback to a pure Ruby implementation in that case. I created a "optional_build" task to do this by subclassing Thermite::Tasks, but I suspect there are a bunch of use cases for something like this.

**Comment by malept** [comment]
I think that the way that I've designed the build system so far, a new config option would be the best way to go. Do you want to take a crack at implementing this?

**Comment by nomoon** [comment]
I definitely could. Do you have a preferred behaviour beyond "build if Rust/Cargo is available but succeed even if it's not?"

**Comment by malept** [comment]
Here's what the documentation should look like:

> * `fail_if_cargo_not_found` - whether to exit with a non-zero status code if `cargo` cannot be found and either `github_releases` is `false` or `github_releases` is `true` and no releases could be found. Defaults to `true`.

...I think that documentation needs to be reworded a bit, but hopefully you get the idea.

**Comment by nomoon** [comment]
Whoops! Ok, let me update the PR then 💃

**Comment by nomoon** [comment]
Whoops! Guess I got to eager. Will update the PR shortly.

**Comment by malept** [comment]
Please make sure to follow the pull request directions in the [CONTRIBUTING docs](https://github.com/malept/thermite/blob/master/CONTRIBUTING.md#filing-pull-requests).

**Comment by nomoon** [comment]
There. It was more straightforward to assume that no option set means "behave as normal" and that setting the option simply suppresses the build exception.
